apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: news-explorer
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/khainouski/news-platform-deploy.git
    targetRevision: main
    path: apps/news-explorer
    helm:
      values: |
        image:
          tag: "sha-c0f8014"
        ingress:
          host: goskills.xyz

  destination:
    server: https://kubernetes.default.svc
    namespace: apps

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
