{
 "title": "Distributed Tracing & Logs",
 "description": "Distributed Tracing (Tempo) & Logs (Loki)",
 "tags": [
  "tracing",
  "logs"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "http_method", "query": "GET, POST, PUT, DELETE" },
   { "name": "status_code", "query": "200, 201, 400, 404, 500" }
  ]
 },
 "panels": [
  { "title": "OpenTelemetry (Tempo)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS by HTTP Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"user-service\" && span.http.request.method =~ \"GET|POST|PUT|DELETE\"} | rate() by (span.http.request.method)",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "RPS by Status: $status_code & Method: $http_method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "limit": 50,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"user-service\" && span.http.request.method = \"$http_method\" && span.http.response.status_code = $status_code} | rate() by (span.http.request.method, span.http.response.status_code)",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Latency ($http_method)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{span.http.response.status_code=$status_code && span.http.request.method=\"$http_method\"} | quantile_over_time(duration, .999, .99, .95)",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Error RPS (status >= 400)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{span.http.response.status_code>=400} | rate()",
     "tableType": "traces"
    }
   ]
  },
  { "title": "Logs (Loki)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "RPS by Method (Logs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(rate({app=\"user-service\"} | json | method!=\"\" [1m])) by (method)"
    }
   ]
  },
  {
   "title": "RPS by Status & Method (Logs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(rate({app=\"user-service\"} | json | code = $status_code | method = \"$http_method\" [1m])) by (method, code)",
     "legendFormat": "{{method}} {{code}}"
    }
   ]
  },
  {
   "title": "Error Rate (Logs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "(sum(rate({app=\"user-service\"} | json | code != \"200\" [1m])) / sum(rate({app=\"user-service\"}[1m]))) * 100"
    }
   ]
  }
 ]
}